title: "AI for Urban Planning"
description: >-
  AAAI 2025 Workshop on AI for Urban Planning
url: "https://aifordataediting.github.io"
baseurl: "/AI-for-data-editing"

theme: minima
plugins:
  - jekyll-seo-tag


# 启用SCSS处理
sass:
  sass_dir: assets/css
  style: compressed

# 自定义变量
primary_color: "#198754"  # Bootstrap绿色
